---
- name: Prepare for a full HDP install
  hosts: all
  become: true
  tasks:
  - name: Set authorized key took from file
    authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  - name: Install libselinux-python
    package: name=libselinux-python state=latest
  - name: diable SElinux
    selinux: state=disabled
  - name: set /etc/hosts
    template: src=files/hosts dest=/etc/hosts owner=root group=root mode=0644
  - name: set ulimit to 10000
    shell: ulimit -n 10000
  - name: install ntp
    package: name=ntp state=latest
  - name: start ntp
    service: name=ntpd state=started enabled=yes
  - name: Install HDP repo
    yum_repository:
      name: Ambari
      description: ambari-2.5.0.3 - Updates
      file: ambari.repo
      baseurl: http://alt-bdp-mgt-010.corp.telenor.no/ambari/2.5.0.3
      gpgcheck: no
      gpgkey: http://alt-bdp-mgt-010.corp.telenor.no/ambari/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
      priority: 1

  - name: install ambari-agent
    package: name=ambari-agent state=latest
    
  - name: Configure ambari-agent to see ambari-server
    lineinfile: "dest=/etc/ambari-agent/conf/ambari-agent.ini state=present regexp='^hostname' line='hostname={{ hostvars[groups['ambari'][0]]['hn'] }}.{{domain}}'"

  - name: start ambari-agent
    service: name=ambari-agent state=start